version: "3.8" 

services:
  portainer:
    ports:
      - "9000:9000"  
  
  node:
    ports:
      - "1340:1340"
      - "9230:9230"
    
  mariadb:
    ports:
      - "3306:3306"

  phpmyadmin:
    ports:
      - "9091:80"

  redis:
    ports:
      - "6379:6379"

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"
